### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by Currypan1229** [Aspw-w/ViaForgePlus#7]
Server-IP: rearth.xyz:25565
Server-Version: 1.20.4
Client-Version: 1.8.9

Mods: NightX, Laplus
```
[19:34:41] [Client thread/INFO]: Connecting to rearth.xyz, 25565
[19:34:42] [Netty Client IO #3/ERROR]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$1351/661717400
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:4.0.23.Final]
	at net.raphimc.vialoader.netty.ViaDecoder.channelRead(ViaDecoder.java:56) ~[ViaDecoder.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$1351/661717400
Caused by: java.lang.NullPointerException
	at com.viaversion.viaversion.api.data.BiMappingsBase.getNewId(BiMappingsBase.java:42) ~[BiMappingsBase.class:?]
	at com.viaversion.viaversion.api.data.FullMappingsBase.getNewId(FullMappingsBase.java:100) ~[FullMappingsBase.class:?]
	at com.viaversion.viabackwards.api.data.BackwardsMappings.getNewItemId(BackwardsMappings.java:134) ~[BackwardsMappings.class:?]
	at com.viaversion.viaversion.rewriter.TagRewriter.handle(TagRewriter.java:189) ~[TagRewriter.class:?]
	at com.viaversion.viaversion.rewriter.TagRewriter.lambda$getGenericHandler$2(TagRewriter.java:158) ~[TagRewriter.class:?]
	at com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.lambda$registerPackets$11(Protocol1_20To1_20_2.java:157) ~[Protocol1_20To1_20_2.class:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:399) ~[AbstractProtocol.class:?]
	at com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.transform(Protocol1_20To1_20_2.java:180) ~[Protocol1_20To1_20_2.class:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[PacketWrapperImpl.class:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:120) ~[ProtocolPipelineImpl.class:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[UserConnectionImpl.class:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[UserConnectionImpl.class:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[UserConnection.class:?]
	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:45) ~[ViaDecoder.class:?]
	at net.raphimc.vialoader.netty.ViaDecoder.decode(ViaDecoder.java:30) ~[ViaDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:4.0.23.Final]
	... 23 more
```

**Comment by Currypan1229** [comment]
もしほかの人が発生しないようでしたら、閉じていただいて結構です。
こちらの環境はいろいろと悪いところがありますので

**Comment by Currypan1229** [comment]
アプデしたらなくなりました
